### PR TITLE
Initial structure for DDS Mesos Plugin

### PR DESCRIPTION
**Pull request by kvnnap**
Up till now we have a working version of a small prototype of Mesos framework for DDS.
To run this using two cores, use 

`dds-submit -r mesos -n 2.`

Then, set and activate a topology normally. This was tested with the following topology:

```
<topology id="myTopology">

   <!-- Definition of tasks, properties and collections | app1 -l -n --taskIndex %taskIndex% --collectionIndex %collectionIndex% -->
   <var id="appNameVar" value="/bin/sleep 122" />

   <property id="property1" />
   <property id="property2" />

   <decltask id="task3">
      <exe reachable="true">${appNameVar}</exe>
      <properties>
         <id access="read">property1</id>
         <id access="readwrite">property2</id>
      </properties>
   </decltask>

   <decltask id="task4">
      <exe>/bin/sleep 123</exe>
      <properties>
         <id access="write">property1</id>
      </properties>
   </decltask>

   <!-- Definition of the topology itself, where also groups can be defined -->
   <main id="main">
      <task>task3</task>
      <task>task4</task>
   </main>

</topology>
```

Currently, the dds-submit command spawns agents and then blocks throughout the lifetime of these agents. This is due to a limitation we have found that requires us to **separate** the Mesos framework from the DDS Intercom callback functions which are registered on dds-submit. Tests have shown that the DDS callback functions are not shared between separate dds-submit requests. This means that multiple dds-submit calls will launch multiple instances of the DDS Mesos framework, and ideally we want only one instance running throughout the system.

We may need to separate these by having a service running which receives dds-submit requests and using the same Mesos instance, spawns new dds-agents accordingly.

### CODE REVIEW

**Comment by ktf** [comment]
Very nice thanks. This of course will require a bit of cleanup for the hardcoded things. @AnarManafov do we understand correctly that we will need to have a separate service? This actually is probably what we want in any case so that we can enforce authentication and quota at the mesos level, rather than having to "trust" a generic DDS user.

**Comment by AnarManafov** [comment]
regarding. blocked dds-submit. This was a bug. We also found it while writing localhost plug-in for DDS. The problem is that sockets by default are inherited by the child processes (after fork). So, commander was thinking that the plug-in is still alive (when actually it finished its job), when it were actually agents alive who inherited sockets of the plug-in. It is only true is you run on a local system and spawn agents using a helper script of a program which use fork. Very tricky "bug". I would not even call it a bug. 
Yesterday we have fixed it. Probably today it will be merged into the master.

**Comment by AnarManafov** [comment]
Reg. "Tests have shown that the DDS callback functions are not shared between separate dds-submit requests. This means that multiple dds-submit calls will launch multiple instances of the DDS Mesos framework, and ideally we want only one instance running throughout the system."

This is intentionally. It is responsibility of a plug-in to handle those calls. For example, users can call dds-submit with ssh and with slur and get a distributed DDS cluster which combines ssh nodes and nodes on a slurm cluster.

Multiple calls to dds-submit, should produce more agents. DDS can dynamically link then together.

**Comment by AnarManafov** [comment]
reg. "We may need to separate these by having a service running which receives dds-submit requests and using the same Mesos instance, spawns new dds-agents accordingly."

Yes, one of the solution. Another solution can be is that you cache the information about submissions. Each new submission your plug-in will read the cache and act accordingly.

So, like I said, it is not dictated by DDS how plug-ins want to do that.

BTW, in the feature we will add dds-submit --clean. In this case plug-in (if it can) should clean working directories of agents it has submitted. We think, that plug-ins should remember at least 10 last agent submissions.

**Comment by AnarManafov** [comment]
BTW, I probably misunderstood your message: "Currently, the dds-submit command spawns agents and then blocks throughout the lifetime of these agents. "

Do you mean you intentionally blocked the plug-in from exiting or it is just happened. Like I said, it can be you face the bug we've just found. But if this is intentional, then forget my first post :)

**Comment by ktf** [comment]
@kvnnap had intentionally blocked the plugin because a Mesos framework is a long-running service.

**Comment by ktf** [comment]
@kvnnap what is the status of the cleanup?

**Pull request merged**
